### ISSUE TITLE
ros descriptions are ignored in deployment process

### ISSUE THREAD

**Issue by smihael** [osrf/gzweb#199]
I'm trying to connect gzweb client to an existing gzserver with a properly spawned robot (I use https://github.com/justagist/panda_simulator).

Even though gzclient shows robot, gzweb does not. When opening JavaScript console in Firefox multiple messages about missing files are reported: 
`ColladaLoader: Couldn't load "http://localhost:8080/assets//franka_panda_description/meshes/visual/link7.dae" (404) gz3d.gui.js:44234:16`

These files are indeed not present in the `http/client/assets/` folder-

In #45 it is mentioned that `GAZEBO_MODEL_PATH` has to be set. In my case this means running:
```
export GAZEBO_MODEL_PATH=`rospack find franka_panda_description`:$GAZEBO_MODEL_PATH
```
Having done that, I ran `npm run deploy --- -m local` again and the script logs `franka_ros_interface ignored. Looking into [get_local_models.py](https://github.com/osrf/gzweb/blob/gzweb_1.4.1/get_local_models.py) shows that packages without _model.config_ file are ignored. 

However this is the case for many ROS packages for spawning models in gazebo (e.g. https://github.com/openrobotics/talos_description).

**Comment by chapulina** [comment]
> In #45 it is mentioned that GAZEBO_MODEL_PATH has to be set.
> packages without model.config file are ignored.

On #45 they also mention the need to add a `model.config` file, it looks like that's how people have been working around this issue.

Maybe the `get_local_models` script can be changed to support models without `model.config` while retaining the current functionality. But I'll close this issue because there are already a couple issues about URDF support: #45, #167. Please follow up in one of them.
